version: "3"
services:
  portainer:
    image: "portainer/portainer-ce:latest"
    container_name: "portainer"
    command: "-H unix:///var/run/docker.sock"
    expose:
      - "9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    restart: "unless-stopped"
  xray:
    build: "./xray"
    container_name: "xray"
    expose:
      - "10010"
    volumes:
      - "./xray/data:/etc/xray"
    restart: "unless-stopped"
  nginx:
    image: "nginx:alpine"
    container_name: "nginx"
    ports:
     - "80:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - "portainer"
      - "xray"
    restart: "unless-stopped"

volumes:
  portainer_data: