version: "3"
services:
  filebrowser:
    image: "filebrowser/filebrowser:latest"
    container_name: "filebrowser"
    entrypoint: "/filebrowser --port 80 --baseurl /file --log stdout --database /database/filebrowser.db --root /srv"
    expose:
      - "80"
    volumes:
      - "filebrowser_database:/database"
      - "filebrowser_data:/srv"
      - "./nginx:/srv/nginx"
      - "./xray/confs:/srv/xray"
    restart: "unless-stopped"
  portainer:
    image: "portainer/portainer-ce:latest"
    container_name: "portainer"
    command: "-H unix:///var/run/docker.sock"
    expose:
      - "9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    restart: "unless-stopped"
  xray:
    build: "./xray"
    container_name: "xray"
    expose:
      - "10010"
    volumes:
      - "./xray/confs:/etc/xray/confs"
    restart: "unless-stopped"
  nginx:
    image: "nginx:alpine"
    container_name: "nginx"
    expose:
      - "80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - "portainer"
      - "xray"
    restart: "unless-stopped"
  # cloudflared:
  #   image: "cloudflare/cloudflared:latest"
  #   container_name: "cloudflared"
  #   command: "tunnel run"
  #   environment:
  #     TUNNEL_TOKEN: ""
  #   restart: "unless-stopped"

volumes:
  filebrowser_database:
  filebrowser_data:
  portainer_data:
